admin-console/config/routes.rb
AdminConsole::Engine.routes.draw do
  id_regex = /[^\/]+/
  root :to => "index#index", :via => :get, :as => :admin_console
  post "reload", to: "index#reload"
  get "search", to: "search#index"
  resources :stats, :only => [:index, :show]
  resources :users, :only => [:show], :id => id_regex
  resources :applications, :only => [:show], :id => /.+/
  resources :gears, :only => [:show], :id => id_regex
  resources :nodes, :only => [:show], :id => id_regex
  scope "/capacity" do
    resources :profiles, :only => [:show, :index], :id => id_regex
    get "profiles/:id/nodes", to: "profiles#show_nodes", :id => id_regex, :as => "profile_nodes"
  end
  resources :suggestions, :only => [:index]
end

# integrate admin-console routes into the broker routes.
Rails.application.routes.draw do
      mount AdminConsole::Engine => Rails.application.config.admin_console[:mount_uri]
end

admin-console/app/models/admin_console/bin.rb
module AdminConsole
  Bin = Struct.new(:bin, :count) do
    def self.from_mongo_aggregate(bson)
      new(bson["_id"], bson["count"])
    end
  end
end

admin-console/app/controllers/admin_console/application_controller.rb
module AdminConsole
  class ApplicationController < ActionController::Base
    include Rescue

    layout "admin_console"

    def active_tab
      nil
    end
  end
end

admin-console/app/controllers/admin_console/applications_controller.rb
module AdminConsole
  class ApplicationsController < ApplicationController
    def show
      @id = params[:id]
      #TODO catch mongoid exception when application not found and render 404 page
      #If a url is passed with http:// or https:// then get rid of it, one of the /'s is already stripped off by rails
      @id.gsub! /http(s)?:\//, ""
      begin
        @app = Application.find_by(:$or => [{:_id => @id}, {:name => @id}, {"aliases.fqdn" => @id}])
      rescue Mongoid::Errors::DocumentNotFound => e
        #attempt to match the default fqdn based on app name and domain
        @id.match(/(.+)-([^\.]+)\./) do |m|
          domain = Domain.find_by :namespace => m[2]
          @app = domain.applications.find_by :name => m[1]
        end
        raise e unless defined? @app
      end
    end

    protected
      def page_not_found(e=nil, message=nil, alternatives=nil)
        message = "Application #{@id} not found"
        super(e, message, alternatives)
      end
  end
end

admin-console/app/controllers/admin_console/gears_controller.rb
module AdminConsole
  class GearsController < ApplicationController
    def show
      @id = params[:id]
      app_and_gear = Application.find_by_gear_uuid @id
      @app = app_and_gear[0]
      @gear = app_and_gear[1]
      page_not_found unless @gear.present?
    end

    protected
      def page_not_found(e=nil, message=nil, alternatives=nil)
        message = "Gear #{@id} not found"
        super(e, message, alternatives)
      end
  end
end

admin-console/app/controllers/admin_console/index_controller.rb
module AdminConsole
  class IndexController < ApplicationController
    def index
      @stats = AdminConsole::Stats.systems_summaries
      @stats_created_at = @stats.created_at
      @suggestions = @stats.suggestions
      if (!Rails.env.production?) && n = params[:tsugs]
        @suggestions = Admin::Suggestion::Advisor.subclass_test_instances.
                       slice(0, n.to_i).compact
      end
      @suggestions.sort_by!{ |s| [s.important? ? 0 : 1, s.is_a?(Class) ? s.to_s : s.class.to_s] }

      @config = Rails.application.config.admin_console
      @cache_timeout = @config[:stats][:cache_timeout]
      @active_warning_threshold = @config[:warn][:node_active_remaining]

      @summary_for_profile = @stats.profile_summaries_hash
    end

    def reload
      AdminConsole::Stats.clear
      redirect_to params[:then] || admin_console_path
    end
  end
end

admin-console/app/controllers/admin_console/nodes_controller.rb
module AdminConsole
  class NodesController < ApplicationController
    rescue_from OpenShift::NodeException, :with => :page_not_found

    def show
      @id = params[:id]
      @node = OpenShift::ApplicationContainerProxy.instance(@id).get_node_details %w[
          gears_usage_pct
          gears_active_usage_pct
          max_active_gears
          gears_started_count
          gears_idle_count
          gears_stopped_count
          gears_deploying_count
          gears_unknown_count
          gears_total_count
          gears_active_count
          node_profile
          district_uuid
          district_active
          public_ip
          public_hostname
        ]
    end

    protected
      def page_not_found(e=nil, message=nil, alternatives=nil)
        message = "Node #{@id} did not respond.  It may not exist or is currently unavailable."
        super(e, message, alternatives)
      end
  end
end

admin-console/app/controllers/admin_console/profiles_controller.rb
module AdminConsole
  class ProfilesController < ApplicationController
    respond_to :json, :xml
    def show
      @id = params[:id]
      stats = AdminConsole::Stats.systems_summaries
      @profile = stats[:profile_summaries_hash][@id]
      @stats_created_at = stats[:created_at]

      return page_not_found unless @profile.present?

      load_topology
    end

    def index
      reload = params[:reload]
      stats = AdminConsole::Stats.systems_summaries(reload)
      respond_with stats[:profile_summaries_hash]
    end

    def show_nodes
      @show_nodes = true
      @id = params[:id]
      reload = params[:reload]
      stats = AdminConsole::Stats.systems_summaries(reload)
      @profile = stats[:profile_summaries_hash][@id]
      @stats_created_at = stats[:created_at]

      return page_not_found unless @profile.present?

      load_topology
      render :show
    end

    protected

      def load_topology
        @config = Rails.application.config.admin_console
        @cache_timeout = @config[:stats][:cache_timeout]
        @active_warning_threshold = @config[:warn][:node_active_remaining]

        @undistricted_nodes_exist = @profile[:districts].any? {|district| district[:name] == "(NONE)"}
        @districts_exist = Rails.configuration.msg_broker[:districts][:enabled] &&
                          (@profile[:districts].size > 1 || !@undistricted_nodes_exist)
        @show_nodes |= !@districts_exist

        @active_sort = params[:sk].nil? ? (@show_nodes ? 'active' : 'total') : params[:sk]
        @active_sort_direction = params[:so].nil? ? 'desc' : params[:so]

        if (@show_nodes)
          @nodes = []
          @profile[:districts].each { |district| @nodes.concat district[:nodes] }
          @nodes = @nodes.sort { |x, y| sort_nodes(x, y)}
          @district_uuid_filter = params[:district]
        else
          @districts = @profile[:districts].sort { |x, y| sort_districts(x, y)}
        end
      end

      def page_not_found(e=nil, message=nil, alternatives=nil)
        message = "Gear profile #{@id} not found"
        super(e, message, alternatives)
      end

      def sort_nodes(x, y)
        if @active_sort_direction == 'desc'
          return y[:gears_active_count] <=> x[:gears_active_count]
        end

        x[:gears_active_count] <=> y[:gears_active_count]
      end

      def sort_districts(x, y)
        active_warning_threshold = @config[:warn][:node_active_remaining]
        sort = if @active_sort == 'total'
          if @active_sort_direction == 'desc'
            lambda{ |s| s[:dist_avail_capacity] }
          else
            lambda{ |s| -s[:dist_avail_capacity] }
          end
        else
          if @active_sort_direction == 'desc'
            lambda{ |s| -(active_warning_threshold * s[:nodes].size - s[:available_active_gears_with_negatives]) }
          else
            lambda{ |s| (active_warning_threshold * s[:nodes].size - s[:available_active_gears_with_negatives]) }
          end
        end

        sort.call(x) <=> sort.call(y)
      end
  end
end

admin-console/app/controllers/admin_console/rescue.rb
module AdminConsole
  module Rescue
    extend ActiveSupport::Concern

    included do
      rescue_from Mongoid::Errors::DocumentNotFound, :with => :page_not_found
      rescue_from Mongo::ConnectionFailure, :with => :mongo_connection_failure
      rescue_from Moped::Errors::ConnectionFailure, :with => :mongo_connection_failure
    end

    protected
      def page_not_found(e=nil, message=nil, alternatives=nil)
        @reference_id = request.uuid
        logger.warn "Page not found - Reference ##{@reference_id}"
        @message, @alternatives = message, alternatives
        render 'not_found'
      end

      def mongo_connection_failure(e=nil)
        @reference_id = request.uuid
        logger.warn "Mongo connection failure - Reference ##{@reference_id}"
        @message, @alternatives = "Failed to connect to MongoDB", nil
        render 'error'
      end

      def log_error(e, msg="Unhandled exception")
        logger.error "#{msg} reference ##{request.uuid}: #{e.message}\n#{e.backtrace.join("\n  ")}"
      end
  end
end

admin-console/app/controllers/admin_console/suggestions_controller.rb
module AdminConsole
  class SuggestionsController < IndexController
    def index
      super # same stuff as the index controller for now

      @expanded = params[:expanded]
    end
  end
end

admin-console/app/helpers/admin_console/application_helper.rb
module AdminConsole
  module ApplicationHelper
    include AdminConsole::Html5BoilerplateHelper

    def product_title
      'OpenShift Origin'
    end

    def gear_group_cartridges(app, group_instance)
      group_instance.all_component_instances.map { |component_instance| 
      cart = CartridgeCache.find_cartridge(component_instance.cartridge_name, app)
      
      # Handling the case when component_properties is an empty array
      # This can happen if the mongo document is copied and pasted back and saved using a UI tool
      if component_instance.component_properties.nil? or component_instance.component_properties.is_a? Array
        component_instance.component_properties = {}
      end
       
      component_instance.component_properties.merge({
        :is_sparse => component_instance.is_sparse?,
        :id => component_instance.id,
        :name => cart.name, 
        :display_name => cart.display_name,
        :tags => cart.categories
      }) 
    }
    end
  end
end

admin-console/app/helpers/admin_console/capacity_planning_helper.rb
module AdminConsole
  module CapacityPlanningHelper
    def capacity_overview_sample_profile

      profile = Admin::Stats::HashWithReaders.new.merge({
        :profile => "small",
        :district_count => 24,
        :nodes_count => 72,
        :districts => [],
        :district_capacity => 144000,
        :gears_total_count => 61920,
        :gears_active_count => 5961,
        :available_active_gears_with_negatives => 519,
        :effective_available_gears => 519
      })
      prng = Random.new(11123)
      24.times do |ind|
        nodes = []
        3.times do |ind|
          nodes << {:max_active_gears => 90, :gears_active_usage_pct => prng.rand * 110}
        end
        profile.districts << {:name => ind.to_s, :dist_usage_pct => prng.rand * 100, :nodes => nodes}
      end
      profile
    end

    def sample_tooltip(is_sample, msg_key, classes = [], &block)
      return content_tag(:div, {:class => classes.join(" ").html_safe}, &block) unless is_sample

      message = case msg_key
        when "district_count"
          "The number of districts in this gear size."
        when "total_gears"
          "The total number of gears for this gear size. Includes all active, idled, stopped, deploying, etc. gears."
        when "max_total_gears"
          "Districts have a maximum number of gears that can be added to them. The maximum number of gears for a gear size is the sum of the max for each district in that gear size."
        when "total_progress"
          "This bar indicates the ratio of total gears to max gears for this gear size."
        when "total_heat_map"
          "Each district has a percent usage based on the number of gears already used in the district relative to its maximum. The heat map shows how many districts are at a particular level of percent usage based on the intensity of the color."
        when "node_count"
          "The number of nodes in this gear size."
        when "active_gears"
          "The number of active gears for this gear size. Active gears are allocated system resources."
        when "max_active_gears"
          "Each node has a maximum number of active gears. This maximum is not a hard limit, as idled or stopped gears on the node could become active again. Nodes over their max active gear limit will not accept any new gears. If the maximum number of active gears on the profile has been reached, then either all nodes have reached their maximum active capacity, or some nodes may be over their active capacity."
        when "active_progress"
          "This bar indicates the ratio of active gears to max active gears for this gear size.  If the ratio is above a configurable warning threshold then the portion above the threshold will be shown in orange."
        when "active_heat_map"
          "Each node has a percent active usage based on the number of active gears on the node relative to the maximum active gears allowed. This percentage can be larger than 100%. The heat map shows how many nodes are at a particular level of percent active usage based on the intensity of the color. A configurable warning threshold controls when then nodes transition to orange, and any nodes over 100% active usage will be red."
        else
          ""
        end

      classes << "tooltip-handle"
      content_tag(:div, opts = {
        :class => classes.join(" ").html_safe,
        "data-toggle" => "tooltip",
        :title => message,
        :tabindex => 0
      }, &block)
    end
  end
end

admin-console/app/helpers/admin_console/html5_boilerplate_helper.rb
module AdminConsole
  module Html5BoilerplateHelper
    # Create a named haml tag to wrap IE conditional around a block
    # http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
    def ie_tag(name=:body, attrs={}, &block)
      attrs.symbolize_keys!
      haml_concat("<!--[if lt IE 7]> #{ tag(name, add_class('ie6', attrs), true) } <![endif]-->".html_safe)
      haml_concat("<!--[if IE 7]>    #{ tag(name, add_class('ie7', attrs), true) } <![endif]-->".html_safe)
      haml_concat("<!--[if IE 8]>    #{ tag(name, add_class('ie8', attrs), true) } <![endif]-->".html_safe)
      haml_concat("<!--[if IE 9]>    #{ tag(name, add_class('ie9', attrs), true) } <![endif]-->".html_safe)
      haml_concat("<!--[if gt IE 8]><!-->".html_safe)
      haml_tag name, attrs do
        haml_concat("<!--<![endif]-->".html_safe)
        block.call
      end
    end

    def ie_html(attrs={}, &block)
      ie_tag(:html, attrs, &block)
    end

  private

    def add_class(name, attrs)
      classes = attrs[:class] || ''
      classes.strip!
      classes = ' ' + classes if !classes.blank?
      classes = name + classes
      attrs.merge(:class => classes)
    end
  end
end

admin-console/app/helpers/admin_console/layout_helper.rb
require 'enumerator'
module AdminConsole
  module LayoutHelper

    def navigation_tabs(options={}, &block)
      content = capture(&block)
      content_tag(:ul, content, :class => 'nav')
    end

    def navigation_tab(name, options={})
      action = options[:action]
      active = controller.active_tab == name || (name.to_s == controller_name) && (action.nil? || action.to_s == controller.action_name)
      content_tag(
        :li,
        link_to(
          options[:name] || ActiveSupport::Inflector.humanize(name),
          url_for({
            :action => action || :index,
            :controller => name
          })
        ),
        active ? {:class => 'active'} : nil)
    end

    def progress_bar(percent, classes = [])
      percent = 0.25 if percent < 0.25 #make bar always visible
      percent = 100 if percent > 100
      bar = content_tag(:div, "", :class => "bar", :style => "width: #{percent}%;")
      classes << "progress"
      content_tag(:div, bar, :class => classes.join(' '))
    end

    def progress_bar_with_thresholds(percent, warning, error)
      percent = 0.25 if percent < 0.25 #make bar always visible
      warning = 0.25 if warning < 0.25 #make bar always visible
      error = 0.25 if error < 0.25 #make bar always visible
      percent = 100 if percent > 100
      bars = []
      bars << content_tag(:div, "", :class => "bar bar-success", :style=> "width: #{[percent,warning].min}%;")
      bars << content_tag(:div, "", :class => "bar bar-warning", :style=> "width: #{[percent - warning, error - warning].min}%;") unless percent < warning
      bars << content_tag(:div, "", :class => "bar bar-danger", :style=> "width: #{percent - error}%;") unless percent < error
      content_tag(:div, bars.join.html_safe, :class => "progress")
    end

    def threshold_pct(threshold, total)
      return 0 if total == 0
      ((total - threshold) / total.to_f) * 100
    end

    def log_scale_percentage(perfect, actual, options = {})
      log_pct_increment = options[:log_pct_increment].present? ? options[:log_pct_increment] : 25
      log_base = options[:log_base].present? ? options[:log_base] : 10
      max_pct = options[:max_pct].present? ? options[:max_pct] : 100

      relative = (perfect-actual).abs
      return 0 if relative == 0

      log = Math.log(relative) / Math.log(log_base)
      log = log.ceil
      log = 1 if log == 0 # normalize when relative == 1
      log_position = (log - 1) * log_pct_increment # increases one log every log_pct_increment
      power = log_base ** log
      position = relative / power.to_f * log_pct_increment
      [max_pct, log_position + position].min
    end
  end
end

admin-console/app/views/admin_console/index/_profile.html.haml
- undistricted_nodes_exist = profile[:districts].any? {|district| district[:name] == "(NONE)"}
- show_districts = Rails.configuration.msg_broker[:districts][:enabled] && (profile[:districts].size > 1 || !undistricted_nodes_exist)
- profile_name = profile[:profile]
- sample = false if !defined? sample
.profile{:class => sample ? 'sample' : ''}
  %h3
    = "#{profile_name.capitalize} gears"
  %table{:class => show_districts ? nil : "nodes-only"}
    %tbody
      %tr.districts{:profile_url => sample ? nil : (show_districts ? profile_path(:id => profile_name) : profile_nodes_path(:id => profile_name))}
        %td
          - if show_districts
            = sample_tooltip sample, "district_count" do
              .stat-label
                districts
              .stat-number-large
                = undistricted_nodes_exist ? profile[:district_count] - 1 : profile[:district_count]
            - unless sample
              .hover-action.hidden-mobile
                = link_to "Details...", profile_path(:id => profile_name)
          - else
            .stat-label
              nodes
            .stat-number-large
              = profile[:nodes_count]
        %td
          - gears_total_count = profile[:gears_total_count]
          - district_capacity = profile[:district_capacity]
          - district_capacity = district_capacity == 0 ? 6000 : district_capacity
          - uuid_usage_pct = (gears_total_count.to_f / district_capacity.to_f) * 100
          = sample_tooltip sample, "total_gears", ["pull-left"] do
            .stat-label
              gears
            .stat-number
              = number_with_delimiter(gears_total_count)
          = sample_tooltip sample, "max_total_gears", ["pull-right", "text-right", "muted"] do
            .stat-label
              max gears
            .stat-number
              = number_with_delimiter(district_capacity)
          = sample_tooltip sample, "total_progress", ["progress-tooltip-wrapper"] do
            = progress_bar(uuid_usage_pct, ["progress-inverse"])
          - if show_districts
            = sample_tooltip(sample, "total_heat_map", ["heat-map-line"]) do
              .bar
                - profile[:districts].each do |district|
                  .district.tickmark{:style => "left: #{[0, district[:dist_usage_pct]].max}%;"}
              .end-point-left
                = "0%"
              .label-center
                = "usage by district"
              .end-point-right
                = "100%"
      %tr.nodes{:profile_url => sample ? nil : profile_nodes_path(:id => profile_name)}
        %td
          - if show_districts
            = sample_tooltip sample, "node_count" do
              .stat-label
                nodes
              .stat-number-large
                = profile[:nodes_count]
          - unless sample
            .hover-action.hidden-mobile
              = link_to "Details...", profile_nodes_path(:id => profile_name)
        %td
          - active_gears = profile.gears_active_count
          - total_active_gears = active_gears + profile.effective_available_gears
          - if total_active_gears == 0 # avoid NaN below
            - active_pct = 0.0
          - else
            - active_pct = (active_gears.to_f / total_active_gears.to_f) * 100
          - active_warn_pct = threshold_pct(@active_warning_threshold, total_active_gears)
          = sample_tooltip sample, "active_gears", ["pull-left"] do
            .stat-label
              active 
              %br.hidden
              gears
            .stat-number
              = number_with_delimiter(active_gears)
          = sample_tooltip sample, "max_active_gears", ["pull-right", "text-right", "muted"] do
            .stat-label
              max active
              %br.hidden
              gears
            .stat-number
              = number_with_delimiter(total_active_gears)
          = sample_tooltip sample, "active_progress", ["progress-tooltip-wrapper"] do
            = progress_bar_with_thresholds(active_pct, active_warn_pct, Float::INFINITY)
          = sample_tooltip(sample, "active_heat_map", ["heat-map-line"]) do
            .bar
              - profile[:districts].each do |district|
                - district[:nodes].each do |node|
                  - node_active_warn_pct = threshold_pct(@active_warning_threshold, node[:max_active_gears])
                  - tickmark_class = node[:gears_active_usage_pct] < node_active_warn_pct ? 'tickmark-success' : node[:gears_active_usage_pct] < 100 ? 'tickmark-warning' : 'tickmark-danger';
                  .node.tickmark{:class => tickmark_class, :style => "left: #{[100, node[:gears_active_usage_pct] / 110 * 100].min}%;"}
            .end-point-left
              = "0%"
            .label-center
              = "usage by node"
            .end-point-right
              = "> 110%"
- content_for :javascripts do
  :javascript
    $(function() {
      $('.districts').click(function() {
        if ($(this).attr('profile_url'))
          window.location.href = $(this).attr('profile_url');
      });

      $('.nodes').click(function() {
        if ($(this).attr('profile_url'))
          window.location.href = $(this).attr('profile_url');
      });
    });

admin-console/app/views/admin_console/index/_suggestions.html.haml
%section
  %h3
    Suggestions
  %table{:style => "vertical-align: top;"}
    %tbody
      - @suggestions.each do |suggestion|
        - partial = suggestion_partial_for suggestion
        - url = suggestions_path expanded: suggestion.id, tsugs: params[:tsugs]
        %tr.short.suggestion.clickable{ suggestion_url: url }
          %td
            - if suggestion.important?
              .label.label-important
                = "!"
            - else
              .label.label-info
                = "?"
          %td.suggestion-body       
            = render partial: partial, locals: {suggestion: suggestion, size: :short}

- content_for :javascripts do
  :javascript
    $(function() {
      $('.suggestion').click(function() {
        if ($(this).attr('suggestion_url'))
          window.location.href = $(this).attr('suggestion_url');
      });
    });

admin-console/app/views/admin_console/index/_welcome.html.haml
.hero-unit.welcome.clear
  %h1
    %span
      ="Welcome to the"
    = image_tag "admin_console/openshift-logo-horizontal.svg", :class => "brand"
    = "Administration Console"
%p.lead
  The OpenShift Admin Console gives you fast access to users, apps, gears, and nodes.
.row
  .span6
    %section
      %h3
        What should I do first?
      Create at least one district for each gear profile. Then, create at least one node per gear profile, and add it to a district.  
    %section
      %h3
        What can I expect to see?
      %p
        There are no nodes configured in this deployment yet.  Once your system has nodes configured, you will see an overview of the capacity for each gear size, similar to the one shown below.  Hover over the elements of the overview to see explanations.
    %section
      %h5
        %em
          Sample overview
      = render :partial => 'profile', :locals => {:profile => capacity_overview_sample_profile, :sample => true}
  .span5.offset1
    %section
      %h3
        Terminology
      %dl
        %dt
          Gear Profile (size)
        %dd
          Specifies the parameters provided by the node host, where a single node host can only host a single gear profile.        
        %dt
          District
        %dd
          A set of nodes, and the resource definitions they must share in order to enable transparent migration of gears between hosts.
        %dt
          Node
        %dd
          Host that runs user applications in contained environments called gears.
        %dt
          Gear
        %dd
          Secure container where cartridges are deployed. Gears are isolated from each other through Linux namespacing and SELinux protection. Each gear is given a fair allocation of CPU, memory, disk, and network bandwidth using Linux control groups.
        %dt
          Application
        %dd
          An OpenShift application is code, plus an environment and shared config, with one or more cartridges providing the languages and services that the user's app needs.
        %dt
          Cartridge
        %dd
          Self-contained bit of the application stack like a web server or database that simplifies server maintenance and configuration.

- content_for :javascripts do
  :javascript
    $(function() {
      $(".tooltip-handle").tooltip({
        placement: tooltip_placement
      });

      $(".tooltip-handle").bind("touchstart", function(e){
        $(".tooltip-handle").tooltip('hide');
        $(this).tooltip('show');
        e.stopPropagation();
      }).focus(function(e){
        $(this).tooltip('show');
      }).blur(function(e){
        $(this).tooltip('hide');
      });

      $("body").bind("touchstart", function(){
        $(".tooltip-handle").tooltip('hide');});
    });

admin-console/app/views/admin_console/index/index.html.haml
.capacity
  - if @cache_timeout > 0.seconds
    %small.pull-right.muted
      %form{:action => reload_path, :method => "post"}
        = "Data collected #{time_ago_in_words(@stats_created_at)} ago."
        %button.btn.btn-mini.btn-icon{:type => "submit", :title => "Refresh now."}
          %i.icon-refresh
  - if @summary_for_profile.size == 0 # no profiles to show
    = render :partial => 'welcome'
  - else
    %h1
      System Overview
    .row
      - if @suggestions.size <= 4 # inline suggestions with the profiles 
        - @summary_for_profile.each_with_index do |profile, index|
          .span6{:class => !@suggestions.empty? && index == 1 ? "clear" : ""}
            = render :partial => 'profile', :locals => {:profile => profile[1]}
          - if !@suggestions.empty? && index == 0
            .span6.suggestions-overview
              = render :partial => 'suggestions'
      - else # too many suggestions, put them in the right column
        .span7
          - @summary_for_profile.each_with_index do |profile, index|
            = render :partial => 'profile', :locals => {:profile => profile[1]}
        .span5.suggestions-overview
          = render :partial => 'suggestions'